[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.4"
rand = { version = "0.8.5", default-features = false, features = ["getrandom"]}
clap = { version = "4.5.20", features = ["derive"] }
rayon = "1.10.0"
sdl2 = "0.37.0"